#!/usr/bin/env bash

# EAS Build Post-Install Hook
# This script runs after dependencies are installed
# Removes duplicate PrivacyInfo.xcprivacy files that cause build conflicts

set -e

echo "🔧 EAS Post-Install Hook: Fixing duplicate privacy manifests..."

# Find and remove duplicate PrivacyInfo.xcprivacy files in node_modules
# Keep only the main app's privacy manifest

if [ -d "node_modules" ]; then
  echo "🔍 Searching for duplicate PrivacyInfo.xcprivacy files..."
  
  # Find all PrivacyInfo.xcprivacy files in node_modules
  find node_modules -name "PrivacyInfo.xcprivacy" -type f | while read -r file; do
    echo "📄 Found: $file"
    # Remove duplicate privacy manifests from dependencies
    # The app's own privacy manifest will be generated by Expo
    if [[ "$file" == *"node_modules"* ]]; then
      echo "🗑️  Removing duplicate: $file"
      rm -f "$file"
    fi
  done
  
  echo "✅ Duplicate privacy manifests removed"
else
  echo "⚠️  node_modules directory not found, skipping..."
fi

echo "✅ Post-install hook completed"

